server.error.whitelabel.enabled: true
server:
    port: 8080
    connection-timeout: 30000
magicApiConfig:  
    potterApi:
        url: https://www.potterapi.com/v1
        key: $2a$10$XMsa/.OCwOh2rnKd0NpQKen7H.57alzNfubuR8ytGpM1B94mii5rC                                                         
    request:
        timeout: 30000
logging:
    file: magicApi.log

info:
    app:
        name: Magic API
        description: Desafio Dextra
        version: @project.version@
        profile: desenvolvimento

swagger:
    title: Magic API
    description: Desafio Dextra
    version: @project.version@
    termsOfServiceUrl:
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
    protocol: http
